# travis.yml
# Travis configuration file
#
# Author:   Benjamin Bengfort <benjamin@bengfort.com>
# Created:  Sat Sep 14 14:51:08 2013 -0400
#
# Copyright (C) 2013 Bengfort.com
# For license information, see LICENSE.txt
#
# ID: .travis.yml [da7003b] benjamin@bengfort.com $

# Langauge and versions
language: python
python:
    - "3.5"

# Install testing utilities
before_install:
    - pip install nose coverage coveralls

# Installation script
install:
    - "pip install -r requirements.txt"

# Specify Postgres version
addons:
  postgresql: "9.4"

# Create Databases before tests
before_script:
    - psql -c "CREATE DATABASE bengfort;" -U postgres

# Run the tests
script: "make test"

# After the test
after_success: coveralls

# Django environment
env:
    global:
        - DJANGO_SETTINGS_MODULE="bengfort.settings.testing"
        - SECRET_KEY="supersecretsauce"
        - DATABASE_URL=postgres://localhost/bengfort
        - EMAIL_HOST_USER=''
        - EMAIL_HOST_PASSWORD=''
        - GOOGLE_OAUTH2_KEY=''
        - GOOGLE_OAUTH2_SECRET=''

# Testing notifications
notifications:
    email:
        recipients:
            - benjamin@bengfort.com
        on_success: change
        on_failure: always
