# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='views',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
