# home.migrations
# Autogenerated migrations for the home page app.
#
# Author:   Benjamin Bengfort <benjamin@bengfort.com>
# Created:  Fri Nov 11 11:14:35 2016 -0500

#
# Copyright (C) 2016 Bengfort.com
# For license information, see LICENSE.txt
#
# ID: __init__.py [11b57d0] benjamin@bengfort.com $

"""
Autogenerated migrations for the home page app.
"""

##########################################################################
## Imports
##########################################################################
